logging:
   file: logs/application.log
   pattern:
      console: "%d %-5level [%thread] %logger : %msg%n"
      file: "%d %-5level [%thread] %logger : %msg%n"
   level:
      application: Debug
      org.springframework: WARN
      org.eclipse.jetty: WARN
      com.gemalto: Debug
#thread pool   
jobs.threadpool:
  corePoolSize: 20
  maxPoolSize:  100
  queueCapacity: 5000      