spring:
  application:
    name: api-gateway
server:
  port: 5555
zuul:
# routes to serviceId
  routes:
    api-a:
      path: "/api-a/**"
      serviceId: service-A
    api-b:
      path: "/api-b/**"
      serviceId: service-B
# routes to url
    api-a-url:
      path: "/api-a-url/**"
      url: "http://localhost:2222/"
eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:1111/eureka/"